{
 "title": "Solace PubSub+ Cloud",
 "description": "Monitoring dashboard for Solace PubSub+ Cloud",
 "tags": [
  "solace",
  "broker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "vpn_name", "query": { "query": "label_values(vpn_name)" } }
  ]
 },
 "panels": [
  { "title": "Global status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Broker status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_vpn_enabled{instance=\"$instance\",job=\"solace-vpn-std\"}"
    },
    {
     "expr": "solace_vpn_local_status{instance=\"$instance\",job=\"solace-vpn-std\"}"
    },
    {
     "expr": "solace_vpn_operational{instance=\"$instance\",job=\"solace-vpn-std\"}"
    }
   ]
  },
  {
   "title": "solace-vpn-stats status error",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "solace_up{instance=\"$instance\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "solace-vpn-det status error",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "solace_up{instance=\"$instance\",job=\"solace-vpn-det\"}"
    }
   ]
  },
  { "title": "Collector status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "solace-vpn-std status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_up{instance=\"$instance\",job=\"solace-vpn-std\"}"
    }
   ]
  },
  {
   "title": "solace-vpn-stats status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_up{instance=\"$instance\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "solace-vpn-det status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_up{instance=\"$instance\",job=\"solace-vpn-det\"}"
    }
   ]
  },
  {
   "title": "solace-vpn-std status error",
   "type": "table",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "solace_up{instance=\"$instance\",job=\"solace-vpn-std\"}"
    }
   ]
  },
  { "title": "Message spool usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Message spool usage (bytes)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_spool_usage_bytes{instance=\"$instance\",job=\"solace-vpn-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")/label_replace(solace_vpn_spool_quota_bytes{instance=\"$instance\",job=\"solace-vpn-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Message spool usage (msgs)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_vpn_spool_usage_msgs{instance=\"$instance\",job=\"solace-vpn-std\"}"
    }
   ]
  },
  {
   "title": "Total msgs received discarded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_vpn_rx_discarded_msgs_total{instance=\"$instance\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "Total msgs sent discarded",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_vpn_tx_discarded_msgs_total{instance=\"$instance\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "Total msgs sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solace_vpn_tx_msgs_total{instance=\"$instance\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  { "title": "Detected issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Queues without consumer",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "solace_queue_binds{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-det\"}"
    }
   ]
  },
  {
   "title": "Queues with msg-spool usage exceeded",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "solace_queue_msg_spool_usage_exceeded{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "Bridges with max msg OUT exceeded",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "solace_bridge_max_exceeded_msgs_sent{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "Queues with msg redelivered",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "solace_queue_msg_redelivered{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "Discarded IN messages per client",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "solace_client_rx_discarded_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-stats\"}",
     "legendFormat": "({{client_username}}) {{client_name}}"
    }
   ]
  },
  {
   "title": "Discarded OUT messages per client",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "solace_client_tx_discarded_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-stats\"}",
     "legendFormat": "({{client_username}}) {{client_name}}"
    }
   ]
  },
  {
   "title": "Discarded IN messages per bridge",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "solace_bridge_total_ingress_discards{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  {
   "title": "Discarded OUT messages per bridge",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "solace_bridge_total_egress_discards{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-stats\"}"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Queues",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "solace_queue_spool_usage_bytes{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-det\"} / 1048576"
    },
    {
     "expr": "solace_queue_spool_high_water_mark_bytes{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-det\"} / 1048576"
    },
    {
     "expr": "solace_queue_spool_quota_bytes{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-det\"} / 1048576"
    }
   ]
  },
  { "title": "Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Avg msg rate IN per queue",
   "type": "timeseries",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solace_queue_rx_msg_rate{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-det\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Avg msg rate OUT per queue",
   "type": "timeseries",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solace_queue_tx_msg_rate{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace-vpn-det\"}",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solace_vpn_connections{instance=\"$instance\",job=\"solace-vpn-std\"}",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=\"$instance\",vpn_name!~\"^#.+\",job=\"solace-vpn-stats\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=\"$instance\",vpn_name!~\"^#.+\",job=\"solace-vpn-stats\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Transfer msgs IN",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_msgs_total{instance=\"$instance\",vpn_name!~\"^#.+\",job=\"solace-vpn-stats\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Transfer msgs OUT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_msgs_total{instance=\"$instance\",vpn_name!~\"^#.+\",job=\"solace-vpn-stats\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  }
 ]
}